### ISSUE TITLE
Se deben mejorar las descripciones de los casos de prueba

### ISSUE THREAD

**Issue by evolentini** [gustavobastian/TestingIoTTP2#7]
https://github.com/gustavobastian/TestingIoTTP2/blob/2dfc8de0e2eec6ea056d58a593a303f784650de1/test/specs.js#L161
https://github.com/gustavobastian/TestingIoTTP2/blob/2dfc8de0e2eec6ea056d58a593a303f784650de1/test/specs.js#L182
https://github.com/gustavobastian/TestingIoTTP2/blob/2dfc8de0e2eec6ea056d58a593a303f784650de1/test/specs.js#L211
https://github.com/gustavobastian/TestingIoTTP2/blob/2dfc8de0e2eec6ea056d58a593a303f784650de1/test/specs.js#L240
https://github.com/gustavobastian/TestingIoTTP2/blob/2dfc8de0e2eec6ea056d58a593a303f784650de1/test/specs.js#L272
https://github.com/gustavobastian/TestingIoTTP2/blob/2dfc8de0e2eec6ea056d58a593a303f784650de1/test/specs.js#L301

**Comment by gustavobastian** [comment]
Done
